// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blog: create.doc("blog", {"ai-integration-in-modern-web-apps.mdx": () => import("../content/blog/ai-integration-in-modern-web-apps.mdx?collection=blog"), "building-modern-applications-with-shadcn-ui.mdx": () => import("../content/blog/building-modern-applications-with-shadcn-ui.mdx?collection=blog"), "carve-out-space-for-opportunity-and-coffee.mdx": () => import("../content/blog/carve-out-space-for-opportunity-and-coffee.mdx?collection=blog"), "complete-guide-to-react-server-components-in-nextjs.mdx": () => import("../content/blog/complete-guide-to-react-server-components-in-nextjs.mdx?collection=blog"), "core-web-vitals-developer-action-plan.mdx": () => import("../content/blog/core-web-vitals-developer-action-plan.mdx?collection=blog"), "design-systems-explained-how-to-build-one-that-scales.mdx": () => import("../content/blog/design-systems-explained-how-to-build-one-that-scales.mdx?collection=blog"), "from-idea-to-mvp-how-a-digital-product-agency-accelerates-your-launch.mdx": () => import("../content/blog/from-idea-to-mvp-how-a-digital-product-agency-accelerates-your-launch.mdx?collection=blog"), "how-to-build-a-high-performance-web-app.mdx": () => import("../content/blog/how-to-build-a-high-performance-web-app.mdx?collection=blog"), "letter-club-ode-to-the-slow-web.mdx": () => import("../content/blog/letter-club-ode-to-the-slow-web.mdx?collection=blog"), "new-design-principles-for-modern-web-apps.mdx": () => import("../content/blog/new-design-principles-for-modern-web-apps.mdx?collection=blog"), "tailwind-css-vs-css-modules-which-should-you-choose.mdx": () => import("../content/blog/tailwind-css-vs-css-modules-which-should-you-choose.mdx?collection=blog"), "ui-ux-design-principles-that-drive-business-results.mdx": () => import("../content/blog/ui-ux-design-principles-that-drive-business-results.mdx?collection=blog"), "vercel-vs-self-hosted-nextjs-deployment-strategy.mdx": () => import("../content/blog/vercel-vs-self-hosted-nextjs-deployment-strategy.mdx?collection=blog"), "why-nextjs-is-the-best-framework-for-your-digital-product.mdx": () => import("../content/blog/why-nextjs-is-the-best-framework-for-your-digital-product.mdx?collection=blog"), "why-web-performance-matters.mdx": () => import("../content/blog/why-web-performance-matters.mdx?collection=blog"), }),
};
export default browserCollections;